
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: localhost

development:
  <<: *default
  database: development_estuk

test:
  <<: *default
  database: test_estuk

production:
  <<: *default
  database: production_estuk
